# Generated by Django 5.0.7 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_pairingticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='connecteddevice',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connecteddevice',
            name='session_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
