# Generated by Django 5.2.17 on 2026-09-09 10:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_date', models.DateField(db_index=True)),
                ('consultation_time', models.TimeField(blank=True, null=True)),
                ('consultation_type', models.CharField(db_index=True, default='General', max_length=100)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('discussion', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('advice', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, db_index=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='clients.client')),
            ],
            options={
                'ordering': ['-consultation_date', '-created_at'],
                'indexes': [models.Index(fields=['client', '-consultation_date'], name='consultatio_client__a44f16_idx'), models.Index(fields=['follow_up_required', 'follow_up_date'], name='consultatio_follow__c285e0_idx')],
            },
        ),
    ]
