# Generated by Django 5.2.17 on 2026-09-09 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50)),
                ('alternate_phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('dob', models.DateField(blank=True, db_index=True, null=True)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, db_index=True, max_length=255)),
                ('birth_star', models.CharField(blank=True, db_index=True, max_length=100)),
                ('rashi', models.CharField(blank=True, db_index=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('extra_attributes', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'name'], name='clients_cli_user_id_822da7_idx'), models.Index(fields=['user', 'phone'], name='clients_cli_user_id_cd9d11_idx'), models.Index(fields=['user', 'dob'], name='clients_cli_user_id_fdaa44_idx')],
            },
        ),
    ]
